export const listaServicios = [
    { id: 1, titulo: "Registro de la Contabilidad", desc: "Registro de la contabilidad con el más avanzado sistema informático, específico para nuestra gestión, que nos permite informar periódicamente a los /as Propietarios /as de las operaciones realizadas durante ese período y donde detallamos morosos (si los hubiera), ingresos, gastos y saldos." },
    { id: 2, titulo: "Conciliaciones Bancarias", desc: "Conciliaciones bancarias de las cuentas corrientes, estando conectados, previa autorización de la Comunidad, a través de banca electrónica a las entidades bancarias donde estén las cuentas de la misma para recabar toda la información necesaria en tiempo real." },
    { id: 3, titulo: "Facturación de Cuotas", desc: "Facturación de Cuotas Ordinarias y Extraordinarias, si las hubiera, en recibos mensuales a cada Propietario /a, emitiendo el fichero correspondiente, para el cobro de los recibos domiciliados, que giramos a la entidad bancaria." },
    { id: 4, titulo: "Confección de Presupuestos", desc: "Confección de presupuestos de gastos anuales (llevando un seguimiento comparativo periódicamente, con los gastos reales) y su distribución por coeficientes de participación." },
    { id: 5, titulo: "Gestión de Cobro a Morosos", desc: "Gestiones para cobrar a morosos y demandas de reclamación judicial de cantidades." },
    { id: 6, titulo: "Asesoramiento Jurídico y Técnico", desc: "Asesoramiento jurídico y técnico. Desempeñamos las funciones de Secretario, asistiendo a las Juntas y levantando las actas correspondientes." },
    { id: 7, titulo: "Reclamaciones a Aseguradoras", desc: "Reclamaciones a las Compañías Aseguradoras de las indemnizaciones que por siniestros sufridos por la Comunidad le correspondan a ésta y estudio de los condicionados, franquicias, coberturas y primas para conseguir la mejor opción en beneficio del cliente." },
    { id: 8, titulo: "Servicios Técnicos Cualificados", desc: "Requerir los servicios técnicos cualificados para la reparación inmediata de ascensores, interfonos, instalaciones de televisión, fontanería, electricidad, cerrajería, albañilería, impermeabilización, etc., para lo cual disponemos de profesionales de total confianza y competencia." },
    { id: 9, titulo: "Custodia y Archivo", desc: "Custodia y archivo de todos los documentos de la Comunidad a disposición de los copropietarios /as que los requieran." },
    { id: 10, titulo: "Información General Online", desc: "Acceso a la información general de la Comunidad (estatutos, convocatorias, actas, estados de cuentas, saldos de propietarios, etc.), así como a los boletines de noticias a través del Despacho Virtual." },
    { id: 11, titulo: "Despacho Virtual 24 Horas", desc: "Podrá comunicarnos incidencias, averías, sugerencias, solicitar certificados, realizar denuncias, el cambio de su domiciliación de pago o de la dirección de su correspondencia, 24 horas al día, 365 días al año." }
];